export interface PortfolioItem {
  id: string
  title: string
  description: string
  category: string
  highlightKeyword?: string
  image: string
  technologies: string[]
  demoUrl?: string
  githubUrl?: string
  completionDate?: string
  longDescription?: string
  features?: string[]
  process?: string
}

export const portfolioItems: PortfolioItem[] = [
  {
    "id": "apps-design", 
    "title": "Financial Apps UI/UX Design", 
    "description": "A sleek and intuitive UI/UX design crafted for a financial application, focusing on user-friendly data visualization, account management, and real-time insights.", 
    "category": "apps-design",
    "highlightKeyword": "Financial Apps", 
    "image": "/design/app-design-1.png", 
    "technologies": ["Figma", "Figjam", "Photoshop", "Google Doc"], 
    "demoUrl": "https://example.com/demo",
    "githubUrl": "https://github.com/example/project",
    "completionDate": "September 2023",
    "features": [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries"
    ]
  },
  {
    "id": "apps-design", 
    "title": "iBanking Apps UI/UX Design", 
    "description": "An intuitive iBanking UI/UX for seamless account management, secure transactions, and clear financial insights.", 
    "category": "apps-design",
    "highlightKeyword": "iBanking Apps", 
    "image": "/design/app-design-2.png", 
    "technologies": ["Figma", "Figjam", "Photoshop", "Google Doc"], 
    "demoUrl": "https://example.com/demo",
    "githubUrl": "https://github.com/example/project",
    "completionDate": "December 2023",
    "features": [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries"
    ]
  },
  {
    "id": "apps-design", 
    "title": "Fitness Apps UI/UX Design", 
    "description": "An intuitive UI/UX design for a fitness app focused on workout tracking, progress insights, and user-friendly navigation.", 
    "category": "apps-design",
    "highlightKeyword": "Fitness Apps", 
    "image": "/design/app-design-3.png", 
    "technologies": ["Figma", "Figjam", "Photoshop", "Google Doc"], 
    "demoUrl": "https://example.com/demo",
    "githubUrl": "https://github.com/example/project",
    "completionDate": "September 2023",
    "features": [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries"
    ]
  },
  {
    "id": "apps-design", 
    "title": "E-commerce Apps UI/UX Design", 
    "description": "Clean and modern UI/UX for an e-commerce app, ensuring smooth browsing, easy checkout, and personalized shopping experience.", 
    "category": "apps-design",
    "highlightKeyword": "E-commerce Apps", 
    "image": "/design/app-design-4.png", 
    "technologies": ["Figma", "Figjam", "Photoshop", "Google Doc"], 
    "demoUrl": "https://example.com/demo",
    "githubUrl": "https://github.com/example/project",
    "completionDate": "September 2023",
    "features": [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries"
    ]
  },
  {
    "id": "apps-design", 
    "title": "Finance Apps UI/UX Design", 
    "description": "Sleek UI/UX for a financial app with clear visuals, easy account management, and real-time insights.", 
    "category": "apps-design",
    "highlightKeyword": "Finance Apps", 
    "image": "/design/app-design-5.png", 
    "technologies": ["Figma", "Figjam", "Photoshop", "Google Doc"], 
    "demoUrl": "https://example.com/demo",
    "githubUrl": "https://github.com/example/project",
    "completionDate": "September 2023",
    "features": [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries"
    ]
  },
  {
    "id": "apps-design", 
    "title": "Chatbot Apps UI/UX Design", 
    "description": "Smart and simple UI/UX for a chatbot app, enabling smooth conversations and quick user support.", 
    "category": "apps-design",
    "highlightKeyword": "Chatbot Apps", 
    "image": "/design/app-design-6.png", 
    "technologies": ["Figma", "Figjam", "Photoshop", "Google Doc"], 
    "demoUrl": "https://example.com/demo",
    "githubUrl": "https://github.com/example/project",
    "completionDate": "September 2023",
    "features": [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries"
    ]
  },
  {
    "id": "apps-design", 
    "title": "Fitness Tracking Apps UI/UX Design", 
    "description": "Clean UI/UX for a fitness app with workout tracking, progress monitoring, and goal setting.", 
    "category": "apps-design",
    "highlightKeyword": "Fitness Tracking Apps", 
    "image": "/design/app-design-7.png", 
    "technologies": ["Figma", "Figjam", "Photoshop", "Google Doc"], 
    "demoUrl": "https://example.com/demo",
    "githubUrl": "https://github.com/example/project",
    "completionDate": "September 2023",
    "features": [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries"
    ]
  },
  {
    "id": "apps-design", 
    "title": "Mental Health Apps UI/UX Design", 
    "description": "Calm and thoughtful UI/UX for a mental health app, supporting mood tracking, journaling, and guided sessions.", 
    "category": "apps-design",
    "highlightKeyword": "Mental Health Apps", 
    "image": "/design/app-design-8.png", 
    "technologies": ["Figma", "Figjam", "Photoshop", "Google Doc"], 
    "demoUrl": "https://example.com/demo",
    "githubUrl": "https://github.com/example/project",
    "completionDate": "September 2023",
    "features": [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries"
    ]
  },
  {
    id: "api-1",
    title: "E-commerce site API",
    description: "Secure payment processing API with multiple provider integrations and e-commerce features.",
    category: "backend-api",
    highlightKeyword: "Payment",
    image: "/web/web-7.webp",
    technologies: ["Node.js", "Express", "Stripe API", "PayPal API"],
    githubUrl: "https://github.com/example/project",
    completionDate: "April 2023",
    features: [
      "Multi-provider payment processing",
      "Webhook integration",
      "Transaction reporting",
      "Fraud detection mechanisms",
    ],
  },
  {
    id: "api-2",
    title: "Inventory Management API",
    description: "inventory management RESTful API with e-commerce features.",
    category: "backend-api",
    highlightKeyword: "Inventory",
    image: "/web/web-8.webp",
    technologies: ["Python", "FastAPI", "Redis", "Docker"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "September 2023",
    features: [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries",
    ],
  },
  {
    id: "api-3",
    title: "Inventory Management API",
    description: "inventory management RESTful API with e-commerce features.",
    category: "backend-api",
    highlightKeyword: "Inventory",
    image: "/web/web-8.webp",
    technologies: ["Python", "FastAPI", "Redis", "Docker"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "September 2023",
    features: [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries",
    ],
  },
  {
    id: "api-4",
    title: "Inventory Management API",
    description: "inventory management RESTful API with e-commerce features.",
    category: "backend-api",
    highlightKeyword: "Inventory",
    image: "/web/web-8.webp",
    technologies: ["Python", "FastAPI", "Redis", "Docker"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "September 2023",
    features: [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries",
    ],
  },
  {
    id: "mobile-1",
    title: "Food Ordering App",
    description: "Mobile application for ordering food with tracking workouts and nutrition with progress analytics.",
    category: "mobile",
    highlightKeyword: "Food",
    image: "/mobile/app-1.png",
    technologies: ["React Native", "Redux", "Firebase"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "March 2023",
    features: [
      "Workout tracking and planning",
      "Nutrition logging and analysis",
      "Progress visualization",
      "Social sharing capabilities",
    ],
  },
  {
    id: "mobile-2",
    title: "E-commerce App",
    description: "e-commerce app with payment processing and inventory management.",
    category: "mobile",
    highlightKeyword: "E-commerce",
    image: "/mobile/app-2.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-3",
    title: "Finance App",
    description: "finance app with stock market analysis and portfolio management.",
    category: "mobile",
    highlightKeyword: "Finance",
    image: "/mobile/app-3.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-4",
    title: "Weather App",
    description: "weather app with weather forecast and location tracking.",
    category: "mobile",
    highlightKeyword: "Weather",
    image: "/mobile/app-4.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-5",
    title: "Event Booking App",
    description: "event booking app with event planning and management.",
    category: "mobile",
    highlightKeyword: "Events",
    image: "/mobile/app-5.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-6",
    title: "Travel & Tour Guide App",
    description: "travel & tour guide app with travel planning and management.",
    category: "mobile",
    highlightKeyword: "Travel",
    image: "/mobile/app-6.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-7",
    title: "E-commerce App",
    description: "ecommerce app with e-commerce features.",
    category: "mobile",
    highlightKeyword: "E-commerce",
    image: "/mobile/app-7.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-8",
    title: "Food Recipe App",
    description: "food recipe app with food recipe features.",
    category: "mobile",
    highlightKeyword: "Recipes",
    image: "/mobile/app-8.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "frontend-1",
    title: "Web Application",
    description: "Web application with modern design and responsive layout.",
    category: "frontend",
    highlightKeyword: "Web",
    image: "/web/web-1.webp",
    technologies: ["React.js", "Next.js", "Tailwind CSS", "TypeScript"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "January 2023",
    features: [
      "Interactive data visualizations",
      "Real-time data updates",
      "Customizable dashboard layouts",
      "Export and reporting capabilities",
    ],
  },
  {
    id: "frontend-2",
    title: "E-commerce Platform",
    description: "E-commerce platform with e-commerce features.",
    category: "frontend",
    highlightKeyword: "E-commerce",
    image: "/web/web-2.jpg",
    technologies: ["Vue.js", "Vuex", "SCSS"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "May 2023",
    features: [
      "Course content management",
      "Progress tracking and analytics",
      "Interactive quizzes and assessments",
      "Certificate generation",
    ],
  },
  {
    id: "frontend-3",
    title: "Sports Application",
    description: "Sports application with sports features and analytics.",
    category: "frontend",
    highlightKeyword: "Sports",
    image: "/web/web-3.jpg",
    technologies: ["Vue.js", "Nuxt.js", "SCSS", "TypeScript"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "May 2023",
    features: [
      "Course content management",
      "Progress tracking and analytics",
      "Interactive quizzes and assessments",
      "Certificate generation",
    ],
  },
  {
    id: "frontend-4",
    title: "Deshboard",
    description: "Deshboard application with deshboard features and analytics.",
    category: "frontend",
    highlightKeyword: "Dashboard",
    image: "/web/web-4.webp",
    technologies: ["Vue.js", "Nuxt.js", "SCSS", "TypeScript"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "May 2023",
    features: [
      "Course content management",
      "Progress tracking and analytics",
      "Interactive quizzes and assessments",
      "Certificate generation",
    ],
  },
  {
    id: "nocode-1",
    title: "Customar Relationship",
    description: "No-code solution for client .",
    category: "nocode",
    highlightKeyword: "CRM",
    image: "/no-code/nc-1.webp",
    technologies: ["Webflow", "Airtable", "Zapier"],
    demoUrl: "https://example.com/demo",
    completionDate: "February 2023",
    features: [
      "Client onboarding workflow",
      "Document sharing and management",
      "Automated notifications",
      "Client feedback collection",
    ],
  },
  {
    id: "nocode-2",
    title: "Wordpress AI theme",
    description: "Wordpress AI theme with AI features and easy to manage.",
    category: "nocode",
    highlightKeyword: "AI",
    image: "/no-code/nc-2.webp",
    technologies: ["Bubble", "Stripe", "Memberstack"],
    demoUrl: "https://example.com/demo",
    completionDate: "July 2023",
    features: [
      "Subscription management",
      "Content access control",
      "Member directory and profiles",
      "Integrated payment processing",
    ],
  },
  {
    id: "nocode-2",
    title: "Wordpress AI theme",
    description: "Wordpress AI theme with AI features and easy to manage.",
    category: "nocode",
    highlightKeyword: "AI",
    image: "/no-code/nc-2.webp",
    technologies: ["Bubble", "Stripe", "Memberstack"],
    demoUrl: "https://example.com/demo",
    completionDate: "July 2023",
    features: [
      "Subscription management",
      "Content access control",
      "Member directory and profiles",
      "Integrated payment processing",
    ],
  },
  {
    id: "nocode-2",
    title: "Wordpress AI theme",
    description: "Wordpress AI theme with AI features and easy to manage.",
    category: "nocode",
    highlightKeyword: "AI",
    image: "/no-code/nc-2.webp",
    technologies: ["Bubble", "Stripe", "Memberstack"],
    demoUrl: "https://example.com/demo",
    completionDate: "July 2023",
    features: [
      "Subscription management",
      "Content access control",
      "Member directory and profiles",
      "Integrated payment processing",
    ],
  },
]


export const sectionInfo = {
  "backend": {
    "title": "Backend Projects",
    "description": "Explore my backend projects with a focus on scalability and performance."
  },
  "mobile": {
    "title": "Mobile Projects",
    "description": "Discover my mobile app projects with a range of features and capabilities."
  },
  "frontend": {
    "title": "Frontend Projects",
    "description": "Check out my frontend projects with a focus on user experience and design."
  },
  "nocode": {
    "title": "No-code Projects",
    "description": "Explore my no-code projects with a range of features and capabilities."
  },
  "api": {
    "title": "API Projects",
    "description": "Discover my API projects with a focus on scalability and performance."
  }

}
